ALTER TABLE profiles ADD COLUMN accept_terms BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE profiles ADD COLUMN hex_newsletter_opt_in BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE profiles ADD COLUMN dvda_newsletter_opt_in BOOLEAN NOT NULL DEFAULT FALSE;