import type { EngineDefinition } from '@/types/engine';
import { DEFAULT_2D6_DIRECTIONS } from './shared';

export const STANDARD_ENGINE: EngineDefinition = {
  name: 'Standard',
  description: 'A basic numbered hex flower for testing and learning the system.',
  icon: 'hexagon',
  roll: '2d6',
  directions: DEFAULT_2D6_DIRECTIONS,
  start: 1,
  nodes: [
    {
      id: 1,
      label: '1',
      map: {
        up: 4,
        upRight: 3,
        downRight: 3,
        down: 1,
        downLeft: 2,
        upLeft: 2,
      },
    },
    {
      id: 2,
      label: '2',
      map: {
        up: 6,
        upRight: 4,
        downRight: 1,
        down: 17,
        downLeft: 14,
        upLeft: 5,
      },
    },
    {
      id: 3,
      label: '3',
      map: {
        up: 8,
        upRight: 7,
        downRight: 11,
        down: 18,
        downLeft: 1,
        upLeft: 4,
      },
    },
    {
      id: 4,
      label: '4',
      map: {
        up: 9,
        upRight: 8,
        downRight: 3,
        down: 1,
        downLeft: 2,
        upLeft: 6,
      },
    },
    {
      id: 5,
      label: '5',
      map: {
        up: 11,
        upRight: 6,
        downRight: 2,
        down: 12,
        downLeft: 15,
        upLeft: 1,
      },
    },
    {
      id: 6,
      label: '6',
      map: {
        up: 10,
        upRight: 9,
        downRight: 4,
        down: 2,
        downLeft: 5,
        upLeft: 11,
      },
    },
    {
      id: 7,
      label: '7',
      map: {
        up: 14,
        upRight: 1,
        downRight: 12,
        down: 15,
        downLeft: 3,
        upLeft: 8,
      },
    },
    {
      id: 8,
      label: '8',
      map: {
        up: 13,
        upRight: 14,
        downRight: 7,
        down: 3,
        downLeft: 4,
        upLeft: 9,
      },
    },
    {
      id: 9,
      label: '9',
      map: {
        up: 16,
        upRight: 13,
        downRight: 8,
        down: 4,
        downLeft: 6,
        upLeft: 10,
      },
    },
    {
      id: 10,
      label: '10',
      style: {
        backgroundColor: '#7777ff',
        icon: 'rotate-cw',
      },
      map: {
        up: 15,
        upRight: 16,
        downRight: 9,
        down: 6,
        downLeft: 11,
        upLeft: 12,
      },
    },
    {
      id: 11,
      label: '11',
      map: {
        up: 7,
        upRight: 10,
        downRight: 6,
        down: 5,
        downLeft: 12,
        upLeft: 14,
      },
    },
    {
      id: 12,
      label: '12',
      map: {
        up: 15,
        upRight: 11,
        downRight: 5,
        down: 17,
        downLeft: 19,
        upLeft: 7,
      },
    },
    {
      id: 13,
      label: '13',
      map: {
        up: 18,
        upRight: 16,
        downRight: 9,
        down: 8,
        downLeft: 14,
        upLeft: 15,
      },
    },
    {
      id: 14,
      label: '14',
      map: {
        up: 2,
        upRight: 7,
        downRight: 11,
        down: 12,
        downLeft: 17,
        upLeft: 8,
      },
    },
    {
      id: 15,
      label: '15',
      map: {
        up: 19,
        upRight: 18,
        downRight: 13,
        down: 10,
        downLeft: 12,
        upLeft: 17,
      },
    },
    {
      id: 16,
      label: '16',
      map: {
        up: 3,
        upRight: 18,
        downRight: 13,
        down: 9,
        downLeft: 10,
        upLeft: 15,
      },
    },
    {
      id: 17,
      label: '17',
      map: {
        up: 14,
        upRight: 2,
        downRight: 12,
        down: 19,
        downLeft: 17,
        upLeft: 15,
      },
    },
    {
      id: 18,
      label: '18',
      map: {
        up: 16,
        upRight: 3,
        downRight: 15,
        down: 13,
        downLeft: 19,
        upLeft: 18,
      },
    },
    {
      id: 19,
      label: '19',
      map: {
        up: 17,
        upRight: 15,
        downRight: 18,
        down: 19,
        downLeft: 19,
        upLeft: 17,
      },
    },
  ],
};
